### ISSUE TITLE
Checksum for Cask 'flutter' does not match. E

### ISSUE THREAD

**Issue by jiqimaogou** [flschweiger/homebrew-flutter#13]
Error: Checksum for Cask 'flutter' does not match.
Expected: b92ee92b9e8dce901c2425985b3f4a5f9fc8a7d80cb3970c86241c83e70f1a1d
  Actual: 395c44e40399150cddf459216ac4e4d70a1c20b48ac8476576a8b36230c3701e
    File: /Users/hjohnchen/Library/Caches/Homebrew/downloads/c11dd12bb4eb2deff01f5ab98f68abe1089d7889190c77b8b4290dbc5a834dc8--flutter_macos_v1.12.13 hotfix.9-stable.zip

**Comment by flschweiger** [comment]
Thanks for the heads-up, I have updated the checksum 👍
