### ISSUE TITLE
Provide beta option

### ISSUE THREAD

**Issue by gleich** [flschweiger/homebrew-flutter#16]
Provide a cask option that uses the beta release.

**Comment by gleich** [comment]
If you run the cask updates then it is switched to the stable version. It makes much more sense to provide a cask for each channel

**Comment by flschweiger** [comment]
You can now provide an option to directly download the newest release for a specific channel. Since Flutter also updates itself and supports switching of channels, I don't think it makes too much sense to have multiple global installations of Flutter on 
the same machine.
