### ISSUE TITLE
Mismatch SHA-256 checksum

### ISSUE THREAD

**Issue by kihonq** [flschweiger/homebrew-flutter#4]
Error: Checksum for Cask 'flutter' does not match.
Expected: cec91922f563e3a0ff09a5420f8a6eda2a74ce45914a2b008cdf4da97e52c4bd
Actual: 8f7a5cfa1494b6758e1b9b7913871a60934c7f3d487979a6ef176ce4f2a7b4a3

**Comment by gabrielsson** [comment]
#5 Will fix this.

**Comment by flschweiger** [comment]
Thanks for the heads-up @kih0ng & @gabrielsson 😃
Google seems to have replaced or repacked the .zip several times now, checked the new checksum and will merge your PR now. Thanks!
